user:
  max_length_name: 50
  max_length_email: 250
  min_length_password: 6
  max_length_username: 50
  min_length_username: 4
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  username_regex: !ruby/regexp '/\A[a-zA-Z0-9]+\z/'
  default_avt: "default.jpg"
  valid_image_types: ["image/jpeg", "image/gif", "image/png"]
  gender_male: 1
  gender_female: 0
  gender_other: 2
favicon_image: "favicon.png"
